VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	config.vm.box = "hashicorp/precise32"

	config.vm.provider "virtualbox" do |v|
		v.memory = 512
		v.cpus = 1
	end

	### Database instances

	config.vm.define :db do |db_config|
		db_config.vm.network :private_network, :ip => "192.168.33.10"
	end

	config.vm.define :db2 do |db_config|
		db_config.vm.network :private_network, :ip => "192.168.33.11"

		db_config.vm.provision "puppet" do |puppet|
			puppet.manifest_file = "db.pp"
		end
	end

	### Tomcat instances

	config.vm.define :web do |web_config|
		web_config.vm.network :private_network, :ip => "192.168.33.20"
	end

	config.vm.define :web2 do |web_config|
		web_config.vm.network :private_network, :ip => "192.168.33.21"

		web_config.vm.provision "puppet" do |puppet|
			puppet.manifest_file = "web.pp"
		end
	end

end
