VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	config.vm.box = "hashicorp/precise32"

	if Vagrant.has_plugin?("vagrant-librarian-puppet")
		config.librarian_puppet.puppetfile_dir = "librarian"
	end

	config.vm.provider "virtualbox" do |v|
		v.memory = 384
		v.cpus = 1
	end

	config.vm.define :db do |db_config|
		db_config.vm.network :private_network, :ip => "192.168.33.10"

		db_config.vm.provision "puppet" do |puppet|
			puppet.module_path = ["modules", "librarian/modules"]
			puppet.manifest_file = "db.pp"
		end
	end

	config.vm.define :web do |web_config|
		web_config.vm.network :private_network, :ip => "192.168.33.20"

		web_config.vm.provision "puppet" do |puppet|
			puppet.module_path = ["modules", "librarian/modules"]
			puppet.manifest_file = "web.pp"
		end
	end

	config.vm.define :ci do |ci_config|
		ci_config.vm.network :private_network, :ip => "192.168.33.30"

		ci_config.vm.provider "virtualbox" do |vb|
			vb.customize ["modifyvm", :id, "--memory", "1024"]
		end

		ci_config.vm.provision "puppet" do |puppet|
			puppet.module_path = ["modules", "librarian/modules"]
			puppet.manifest_file = "ci.pp"
		end
	end
end
