VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	config.vm.box = "hashicorp/precise32"

	config.vm.provider "virtualbox" do |v|
		v.memory = 256
		v.cpus = 1
	end

	config.vm.define :ansible1 do |c|
		c.vm.network :private_network, :ip => "192.168.10.1"
	end
end

